//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainForm_BuildCancel {
            get {
                return ResourceManager.GetString("MainForm_BuildCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string MainForm_BuildCancelled {
            get {
                return ResourceManager.GetString("MainForm_BuildCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building time.
        /// </summary>
        internal static string MainForm_BuildingTime {
            get {
                return ResourceManager.GetString("MainForm_BuildingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build map.
        /// </summary>
        internal static string MainForm_BuildStart {
            get {
                return ResourceManager.GetString("MainForm_BuildStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates are not valid.
        /// </summary>
        internal static string MainForm_CoordinatesNotValid {
            get {
                return ResourceManager.GetString("MainForm_CoordinatesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty cache.
        /// </summary>
        internal static string MainForm_EmptyCacheButton {
            get {
                return ResourceManager.GetString("MainForm_EmptyCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty the cache.
        /// </summary>
        internal static string MainForm_EmptyCacheHeader {
            get {
                return ResourceManager.GetString("MainForm_EmptyCacheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all tiles from the cache?.
        /// </summary>
        internal static string MainForm_EmptyCacheMessage {
            get {
                return ResourceManager.GetString("MainForm_EmptyCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured with the message.
        /// </summary>
        internal static string MainForm_ErrorOccuredWithMessage {
            get {
                return ResourceManager.GetString("MainForm_ErrorOccuredWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map size. Width and Height should be more than zero.
        /// </summary>
        internal static string MainForm_Exception_InvalidMapSize {
            get {
                return ResourceManager.GetString("MainForm_Exception_InvalidMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMap.
        /// </summary>
        internal static string MainForm_FormTitle {
            get {
                return ResourceManager.GetString("MainForm_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left top latitude.
        /// </summary>
        internal static string MainForm_LeftTopLatitude {
            get {
                return ResourceManager.GetString("MainForm_LeftTopLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left top longitude.
        /// </summary>
        internal static string MainForm_LeftTopLongitude {
            get {
                return ResourceManager.GetString("MainForm_LeftTopLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter map&apos;s file name. It&apos;ll be saved to default directory with the name {0}.
        /// </summary>
        internal static string MainForm_MapPathNotEntered {
            get {
                return ResourceManager.GetString("MainForm_MapPathNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string MainForm_Path {
            get {
                return ResourceManager.GetString("MainForm_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google hybrid.
        /// </summary>
        internal static string MainForm_Providers_GoogleHybrid {
            get {
                return ResourceManager.GetString("MainForm_Providers_GoogleHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        internal static string MainForm_Providers_GoogleMap {
            get {
                return ResourceManager.GetString("MainForm_Providers_GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google satellite.
        /// </summary>
        internal static string MainForm_Providers_GoogleSatellite {
            get {
                return ResourceManager.GetString("MainForm_Providers_GoogleSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yandex hybrid.
        /// </summary>
        internal static string MainForm_Providers_YandexHybrid {
            get {
                return ResourceManager.GetString("MainForm_Providers_YandexHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yandex map.
        /// </summary>
        internal static string MainForm_Providers_YandexMap {
            get {
                return ResourceManager.GetString("MainForm_Providers_YandexMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yandex satellite.
        /// </summary>
        internal static string MainForm_Providers_YandexSatellite {
            get {
                return ResourceManager.GetString("MainForm_Providers_YandexSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right bottom latitude.
        /// </summary>
        internal static string MainForm_RightBottomLatitude {
            get {
                return ResourceManager.GetString("MainForm_RightBottomLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right bottom longitude.
        /// </summary>
        internal static string MainForm_RightBottomLongitude {
            get {
                return ResourceManager.GetString("MainForm_RightBottomLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string MainForm_Source {
            get {
                return ResourceManager.GetString("MainForm_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string MainForm_Warning {
            get {
                return ResourceManager.GetString("MainForm_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string MainForm_Zoom {
            get {
                return ResourceManager.GetString("MainForm_Zoom", resourceCulture);
            }
        }
    }
}
